Feat/nexus [Do not merge]
bcnmy/documentation pull request #47
Opened 2024-09-23 11:04 UTC by joepegler

## PR-Codex overview
This PR focuses on enhancing documentation for the `Biconomy` SDK and `Nexus SDK`, including quickstart guides and code examples, as well as making minor updates to the sidebar and `package.json` dependencies.

### Detailed summary
- Added a quickstart guide for `React` in `docs/pages/quickstart-react.mdx`.
- Added a quickstart guide for `Nexus SDK` in `docs/pages/nexus/quickstart.mdx`.
- Updated sidebar links in `vocs.config.ts` for clarity.
- Modified `package.json` to include `nexus` as a dependency.
- Introduced a new code example in `docs/pages/nexus/overview.mdx` demonstrating `Nexus SDK` usage.
- Removed outdated code snippets from `docs/pages/nexus/overview.mdx`.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

2024-10-10 04:59 UTC, AUCrypto-bit commented
Noice

2024-10-16 04:51 UTC, AUCrypto-bit requested changes
Can someone set this up for me I been at it for days and only seem to be getting more confused and I might melt into a puddle off goo at this rate trying me best not to turn into a supervillain

2024-10-16 04:51 UTC, AUCrypto-bit commented on docs/pages/nexus/overview.mdx
> +const privateKey = "0x...";
0xfF0d2Cf1E52d2C2865Eba2D3d3BB5e952E2B5C68

2024-10-16 04:51 UTC, AUCrypto-bit commented on docs/pages/nexus/overview.mdx
> +import { http } from "viem";
+import USDC {https://exchange.coinjar.com}from "base"main and as many other networks as you can and relay back to my wallet>

2024-11-04 08:37 UTC, himanshugarg06 commented
@joepegler should we close this PR?

2024-11-04 12:47 UTC, closed without merging